/* TEAM STATISTICS Endpoint*/

//Get All Request
export const TEAM_STATISTICS_REQUEST = 'TEAM_STATISTIC-STATISTICS_REQUEST';
export const TEAM_STATISTICS_SUCCESS = 'TEAM_STATISTIC-STATISTICS_SUCCESS';
export const TEAM_STATISTICS_FAIL = 'TEAM_STATISTIC-STATISTICS_FAIL';

//Post Request
export const TEAM_STATISTIC_ADD_REQUEST = 'TEAM_STATISTIC_ADD_REQUEST';
export const TEAM_STATISTIC_ADD_SUCCESS = 'TEAM_STATISTIC_ADD_SUCCESS';
export const TEAM_STATISTIC_ADD_FAIL = 'TEAM_STATISTIC_ADD_FAIL';
export const TEAM_STATISTIC_ADD_RESET = 'TEAM_STATISTIC_ADD_RESET';

//Get One Request
export const TEAM_STATISTIC_DETAILS_REQUEST = 'TEAM_STATISTIC_DETAILS_REQUEST';
export const TEAM_STATISTIC_DETAILS_SUCCESS = 'TEAM_STATISTIC_DETAILS_SUCCESS';
export const TEAM_STATISTIC_DETAILS_FAIL = 'TEAM_STATISTIC_DETAILS_FAIL';

//PUT/UPDATE Request
export const TEAM_STATISTIC_UPDATE_REQUEST = 'TEAM_STATISTIC_UPDATE_REQUEST';
export const TEAM_STATISTIC_UPDATE_SUCCESS = 'TEAM_STATISTIC_UPDATE_SUCCESS';
export const TEAM_STATISTIC_UPDATE_FAIL = 'TEAM_STATISTIC_UPDATE_FAIL';
export const TEAM_STATISTIC_UPDATE_RESET = 'TEAM_STATISTIC_UPDATE_RESET';

//Delete Request
export const TEAM_STATISTIC_DELETE_REQUEST = 'TEAM_STATISTIC_DELETE_REQUEST';
export const TEAM_STATISTIC_DELETE_SUCCESS = 'TEAM_STATISTIC_DELETE_SUCCESS';
export const TEAM_STATISTIC_DELETE_FAIL = 'TEAM_STATISTIC_DELETE_FAIL';
export const TEAM_STATISTIC_DELETE_RESET = 'TEAM_STATISTIC_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';