/* Contact Information Endpoint*/

//Get All Request
export const CONTACT_INFORMATIONS_REQUEST = 'CONTACT_INFORMATION_REQUEST';
export const CONTACT_INFORMATIONS_SUCCESS = 'CONTACT_INFORMATION_SUCCESS';
export const CONTACT_INFORMATIONS_FAIL = 'CONTACT_INFORMATION_FAIL';

//Post Request
export const CONTACT_INFORMATION_ADD_REQUEST = 'CONTACT_INFORMATION_ADD_REQUEST';
export const CONTACT_INFORMATION_ADD_SUCCESS = 'CONTACT_INFORMATION_ADD_SUCCESS';
export const CONTACT_INFORMATION_ADD_FAIL = 'CONTACT_INFORMATION_ADD_FAIL';
export const CONTACT_INFORMATION_ADD_RESET = 'CONTACT_INFORMATION_ADD_RESET';

//Get One Request
export const CONTACT_INFORMATION_DETAILS_REQUEST = 'CONTACT_INFORMATION_DETAILS_REQUEST';
export const CONTACT_INFORMATION_DETAILS_SUCCESS = 'CONTACT_INFORMATION_DETAILS_SUCCESS';
export const CONTACT_INFORMATION_DETAILS_FAIL = 'CONTACT_INFORMATION_DETAILS_FAIL';

//PUT/UPDATE Request
export const CONTACT_INFORMATION_UPDATE_REQUEST = 'CONTACT_INFORMATION_UPDATE_REQUEST';
export const CONTACT_INFORMATION_UPDATE_SUCCESS = 'CONTACT_INFORMATION_UPDATE_SUCCESS';
export const CONTACT_INFORMATION_UPDATE_FAIL = 'CONTACT_INFORMATION_UPDATE_FAIL';
export const CONTACT_INFORMATION_UPDATE_RESET = 'CONTACT_INFORMATION_UPDATE_RESET';

//Delete Request
export const CONTACT_INFORMATION_DELETE_REQUEST = 'CONTACT_INFORMATION_DELETE_REQUEST';
export const CONTACT_INFORMATION_DELETE_SUCCESS = 'CONTACT_INFORMATION_DELETE_SUCCESS';
export const CONTACT_INFORMATION_DELETE_FAIL = 'CONTACT_INFORMATION_DELETE_FAIL';
export const CONTACT_INFORMATION_DELETE_RESET = 'CONTACT_INFORMATION_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';