/* Manager Endpoint*/

//Get All Request
export const MANAGERS_REQUEST = 'MANAGERS_REQUEST';
export const MANAGERS_SUCCESS = 'MANAGERS_SUCCESS';
export const MANAGERS_FAIL = 'MANAGERS_FAIL';

//Post Request
export const MANAGER_ADD_REQUEST = 'MANAGER_ADD_REQUEST';
export const MANAGER_ADD_SUCCESS = 'MANAGER_ADD_SUCCESS';
export const MANAGER_ADD_FAIL = 'MANAGER_ADD_FAIL';
export const MANAGER_ADD_RESET = 'MANAGER_ADD_RESET';

//Get One Request
export const MANAGER_DETAILS_REQUEST = 'MANAGER_DETAILS_REQUEST';
export const MANAGER_DETAILS_SUCCESS = 'MANAGER_DETAILS_SUCCESS';
export const MANAGER_DETAILS_FAIL = 'MANAGER_DETAILS_FAIL';

//PUT/UPDATE Request
export const MANAGER_UPDATE_REQUEST = 'MANAGER_UPDATE_REQUEST';
export const MANAGER_UPDATE_SUCCESS = 'MANAGER_UPDATE_SUCCESS';
export const MANAGER_UPDATE_FAIL = 'MANAGER_UPDATE_FAIL';
export const MANAGER_UPDATE_RESET = 'MANAGER_UPDATE_RESET';

//Delete Request
export const MANAGER_DELETE_REQUEST = 'MANAGER_DELETE_REQUEST';
export const MANAGER_DELETE_SUCCESS = 'MANAGER_DELETE_SUCCESS';
export const MANAGER_DELETE_FAIL = 'MANAGER_DELETE_FAIL';
export const MANAGER_DELETE_RESET = 'MANAGER_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';