/* Player Endpoint*/

//Get All Request
export const PLAYERS_REQUEST = 'PLAYERS_REQUEST';
export const PLAYERS_SUCCESS = 'PLAYERS_SUCCESS';
export const PLAYERS_FAIL = 'PLAYERS_FAIL';

//Post Request
export const PLAYER_ADD_REQUEST = 'PLAYER_ADD_REQUEST';
export const PLAYER_ADD_SUCCESS = 'PLAYER_ADD_SUCCESS';
export const PLAYER_ADD_FAIL = 'PLAYER_ADD_FAIL';
export const PLAYER_ADD_RESET = 'PLAYER_ADD_RESET';

//Get One Request
export const PLAYER_DETAILS_REQUEST = 'PLAYER_DETAILS_REQUEST';
export const PLAYER_DETAILS_SUCCESS = 'PLAYER_DETAILS_SUCCESS';
export const PLAYER_DETAILS_FAIL = 'PLAYER_DETAILS_FAIL';

//PUT/UPDATE Request
export const PLAYER_UPDATE_REQUEST = 'PLAYER_UPDATE_REQUEST';
export const PLAYER_UPDATE_SUCCESS = 'PLAYER_UPDATE_SUCCESS';
export const PLAYER_UPDATE_FAIL = 'PLAYER_UPDATE_FAIL';
export const PLAYER_UPDATE_RESET = 'PLAYER_UPDATE_RESET';

//Delete Request
export const PLAYER_DELETE_REQUEST = 'PLAYER_DELETE_REQUEST';
export const PLAYER_DELETE_SUCCESS = 'PLAYER_DELETE_SUCCESS';
export const PLAYER_DELETE_FAIL = 'PLAYER_DELETE_FAIL';
export const PLAYER_DELETE_RESET = 'PLAYER_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';