//Get All Request
export const SPONSORS_REQUEST = 'SPONSORS_REQUEST';
export const SPONSORS_SUCCESS = 'SPONSORS_SUCCESS';
export const SPONSORS_FAIL = 'SPONSORS_FAIL';

//Post Request
export const SPONSOR_ADD_REQUEST = 'SPONSOR_ADD_REQUEST';
export const SPONSOR_ADD_SUCCESS = 'SPONSOR_ADD_SUCCESS';
export const SPONSOR_ADD_FAIL = 'SPONSOR_ADD_FAIL';
export const SPONSOR_ADD_RESET = 'SPONSOR_ADD_RESET';

//Get One Request
export const SPONSOR_DETAILS_REQUEST = 'SPONSOR_DETAILS_REQUEST';
export const SPONSOR_DETAILS_SUCCESS = 'SPONSOR_DETAILS_SUCCESS';
export const SPONSOR_DETAILS_FAIL = 'SPONSOR_DETAILS_FAIL';

//PUT/UPDATE Request
export const SPONSOR_UPDATE_REQUEST = 'SPONSOR_UPDATE_REQUEST';
export const SPONSOR_UPDATE_SUCCESS = 'SPONSOR_UPDATE_SUCCESS';
export const SPONSOR_UPDATE_FAIL = 'SPONSOR_UPDATE_FAIL';
export const SPONSOR_UPDATE_RESET = 'SPONSOR_UPDATE_RESET';

//Delete Request
export const SPONSOR_DELETE_REQUEST = 'SPONSOR_DELETE_REQUEST';
export const SPONSOR_DELETE_SUCCESS = 'SPONSOR_DELETE_SUCCESS';
export const SPONSOR_DELETE_FAIL = 'SPONSOR_DELETE_FAIL';
export const SPONSOR_DELETE_RESET = 'SPONSOR_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';