// /* Contract Endpoint*/

//Get All Request
export const CONTRACTS_REQUEST = 'CONTRACTS_REQUEST';
export const CONTRACTS_SUCCESS = 'CONTRACTS_SUCCESS';
export const CONTRACTS_FAIL = 'CONTRACTS_FAIL';

//Post Request
export const CONTRACT_ADD_REQUEST = 'CONTRACT_ADD_REQUEST';
export const CONTRACT_ADD_SUCCESS = 'CONTRACT_ADD_SUCCESS';
export const CONTRACT_ADD_FAIL = 'CONTRACT_ADD_FAIL';
export const CONTRACT_ADD_RESET = 'CONTRACT_ADD_RESET';

//Get One Request
export const CONTRACT_DETAILS_REQUEST = 'CONTRACT_DETAILS_REQUEST';
export const CONTRACT_DETAILS_SUCCESS = 'CONTRACT_DETAILS_SUCCESS';
export const CONTRACT_DETAILS_FAIL = 'CONTRACT_DETAILS_FAIL';

//PUT/UPDATE Request
export const CONTRACT_UPDATE_REQUEST = 'CONTRACT_UPDATE_REQUEST';
export const CONTRACT_UPDATE_SUCCESS = 'CONTRACT_UPDATE_SUCCESS';
export const CONTRACT_UPDATE_FAIL = 'CONTRACT_UPDATE_FAIL';
export const CONTRACT_UPDATE_RESET = 'CONTRACT_UPDATE_RESET';

//Delete Request
export const CONTRACT_DELETE_REQUEST = 'CONTRACT_DELETE_REQUEST';
export const CONTRACT_DELETE_SUCCESS = 'CONTRACT_DELETE_SUCCESS';
export const CONTRACT_DELETE_FAIL = 'CONTRACT_DELETE_FAIL';
export const CONTRACT_DELETE_RESET = 'CONTRACT_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';