// /* Player Contract Endpoint*/

//Get All Request
export const PLAYER_CONTRACTS_REQUEST = 'PLAYER_CONTRACTS_REQUEST';
export const PLAYER_CONTRACTS_SUCCESS = 'PLAYER_CONTRACTS_SUCCESS';
export const PLAYER_CONTRACTS_FAIL = 'PLAYER_CONTRACTS_FAIL';

//Post Request
export const PLAYER_CONTRACT_ADD_REQUEST = 'PLAYER_CONTRACT_ADD_REQUEST';
export const PLAYER_CONTRACT_ADD_SUCCESS = 'PLAYER_CONTRACT_ADD_SUCCESS';
export const PLAYER_CONTRACT_ADD_FAIL = 'PLAYER_CONTRACT_ADD_FAIL';
export const PLAYER_CONTRACT_ADD_RESET = 'PLAYER_CONTRACT_ADD_RESET';

//Get One Request
export const PLAYER_CONTRACT_DETAILS_REQUEST = 'PLAYER_CONTRACT_DETAILS_REQUEST';
export const PLAYER_CONTRACT_DETAILS_SUCCESS = 'PLAYER_CONTRACT_DETAILS_SUCCESS';
export const PLAYER_CONTRACT_DETAILS_FAIL = 'PLAYER_CONTRACT_DETAILS_FAIL';

//PUT/UPDATE Request
export const PLAYER_CONTRACT_UPDATE_REQUEST = 'PLAYER_CONTRACT_UPDATE_REQUEST';
export const PLAYER_CONTRACT_UPDATE_SUCCESS = 'PLAYER_CONTRACT_UPDATE_SUCCESS';
export const PLAYER_CONTRACT_UPDATE_FAIL = 'PLAYER_CONTRACT_UPDATE_FAIL';
export const PLAYER_CONTRACT_UPDATE_RESET = 'PLAYER_CONTRACT_UPDATE_RESET';

//Delete Request
export const PLAYER_CONTRACT_DELETE_REQUEST = 'PLAYER_CONTRACT_DELETE_REQUEST';
export const PLAYER_CONTRACT_DELETE_SUCCESS = 'PLAYER_CONTRACT_DELETE_SUCCESS';
export const PLAYER_CONTRACT_DELETE_FAIL = 'PLAYER_CONTRACT_DELETE_FAIL';
export const PLAYER_CONTRACT_DELETE_RESET = 'PLAYER_CONTRACT_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';