/* Location Endpoint*/

//Get All Request
export const LOCATIONS_REQUEST = 'LOCATIONS_REQUEST';
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCESS';
export const LOCATIONS_FAIL = 'LOCATIONS_FAIL';

//Post Request
export const LOCATION_ADD_REQUEST = 'LOCATION_ADD_REQUEST';
export const LOCATION_ADD_SUCCESS = 'LOCATION_ADD_SUCCESS';
export const LOCATION_ADD_FAIL = 'LOCATION_ADD_FAIL';
export const LOCATION_ADD_RESET = 'LOCATION_ADD_RESET';

//Get One Request
export const LOCATION_DETAILS_REQUEST = 'LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAIL = 'LOCATION_DETAILS_FAIL';

//PUT/UPDATE Request
export const LOCATION_UPDATE_REQUEST = 'LOCATION_UPDATE_REQUEST';
export const LOCATION_UPDATE_SUCCESS = 'LOCATION_UPDATE_SUCCESS';
export const LOCATION_UPDATE_FAIL = 'LOCATION_UPDATE_FAIL';
export const LOCATION_UPDATE_RESET = 'LOCATION_UPDATE_RESET';

//Delete Request
export const LOCATION_DELETE_REQUEST = 'LOCATION_DELETE_REQUEST';
export const LOCATION_DELETE_SUCCESS = 'LOCATION_DELETE_SUCCESS';
export const LOCATION_DELETE_FAIL = 'LOCATION_DELETE_FAIL';
export const LOCATION_DELETE_RESET = 'LOCATION_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';