/* Match Score Endpoint*/

//Get All Request
export const MATCH_SCORES_REQUEST = 'MATCH_SCORES_REQUEST';
export const MATCH_SCORES_SUCCESS = 'MATCH_SCORES_SUCCESS';
export const MATCH_SCORES_FAIL = 'MATCH_SCORES_FAIL';

//Post Request
export const MATCH_SCORE_ADD_REQUEST = 'MATCH_SCORE_ADD_REQUEST';
export const MATCH_SCORE_ADD_SUCCESS = 'MATCH_SCORE_ADD_SUCCESS';
export const MATCH_SCORE_ADD_FAIL = 'MATCH_SCORE_ADD_FAIL';
export const MATCH_SCORE_ADD_RESET = 'MATCH_SCORE_ADD_RESET';

//Get One Request
export const MATCH_SCORE_DETAILS_REQUEST = 'MATCH_SCORE_DETAILS_REQUEST';
export const MATCH_SCORE_DETAILS_SUCCESS = 'MATCH_SCORE_DETAILS_SUCCESS';
export const MATCH_SCORE_DETAILS_FAIL = 'MATCH_SCORE_DETAILS_FAIL';

//PUT/UPDATE Request
export const MATCH_SCORE_UPDATE_REQUEST = 'MATCH_SCORE_UPDATE_REQUEST';
export const MATCH_SCORE_UPDATE_SUCCESS = 'MATCH_SCORE_UPDATE_SUCCESS';
export const MATCH_SCORE_UPDATE_FAIL = 'MATCH_SCORE_UPDATE_FAIL';
export const MATCH_SCORE_UPDATE_RESET = 'MATCH_SCORE_UPDATE_RESET';

//Delete Request
export const MATCH_SCORE_DELETE_REQUEST = 'MATCH_SCORE_DELETE_REQUEST';
export const MATCH_SCORE_DELETE_SUCCESS = 'MATCH_SCORE_DELETE_SUCCESS';
export const MATCH_SCORE_DELETE_FAIL = 'MATCH_SCORE_DELETE_FAIL';
export const MATCH_SCORE_DELETE_RESET = 'MATCH_SCORE_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';