/* Soccer Match Endpoint*/

//Get All Request
export const SOCCER_MATCHES_REQUEST = 'SOCCER_MATCHES_REQUEST';
export const SOCCER_MATCHES_SUCCESS = 'SOCCER_MATCHES_SUCCESS';
export const SOCCER_MATCHES_FAIL = 'SOCCER_MATCHES_FAIL';

//Post Request
export const SOCCER_MATCH_ADD_REQUEST = 'SOCCER_MATCH_ADD_REQUEST';
export const SOCCER_MATCH_ADD_SUCCESS = 'SOCCER_MATCH_ADD_SUCCESS';
export const SOCCER_MATCH_ADD_FAIL = 'SOCCER_MATCH_ADD_FAIL';
export const SOCCER_MATCH_ADD_RESET = 'SOCCER_MATCH_ADD_RESET';

//Get One Request
export const SOCCER_MATCH_DETAILS_REQUEST = 'SOCCER_MATCH_DETAILS_REQUEST';
export const SOCCER_MATCH_DETAILS_SUCCESS = 'SOCCER_MATCH_DETAILS_SUCCESS';
export const SOCCER_MATCH_DETAILS_FAIL = 'SOCCER_MATCH_DETAILS_FAIL';

//PUT/UPDATE Request
export const SOCCER_MATCH_UPDATE_REQUEST = 'SOCCER_MATCH_UPDATE_REQUEST';
export const SOCCER_MATCH_UPDATE_SUCCESS = 'SOCCER_MATCH_UPDATE_SUCCESS';
export const SOCCER_MATCH_UPDATE_FAIL = 'SOCCER_MATCH_UPDATE_FAIL';
export const SOCCER_MATCH_UPDATE_RESET = 'SOCCER_MATCH_UPDATE_RESET';

//Delete Request
export const SOCCER_MATCH_DELETE_REQUEST = 'SOCCER_MATCH_DELETE_REQUEST';
export const SOCCER_MATCH_DELETE_SUCCESS = 'SOCCER_MATCH_DELETE_SUCCESS';
export const SOCCER_MATCH_DELETE_FAIL = 'SOCCER_MATCH_DELETE_FAIL';
export const SOCCER_MATCH_DELETE_RESET = 'SOCCER_MATCH_DELETE_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';